name: Feature Request
description: Suggest a new feature for the project.
title: "[Feature] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form below to request a new feature.

  - type: input
    id: description
    attributes:
      label: Description
      description: What is the feature you'd like to see?
      placeholder: Describe the feature
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why do you need this feature? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Optional — your ideal implementation, mockups, or code
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you thought about other ways to solve the same problem?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - P0
        - P1
        - P2
    validations:
      required: true
